export const pageTitles = {
  dashboard: 'الرئيسية',
  profile: 'بياناتي',
  cars: 'السيارات',
  carNew: 'إضافة سيارة',
  carEdit: 'تعديل سيارة',
  customers: 'العملاء',
  customerNew: 'إضافة عميل',
  customerDetails: 'ملف العميل',
  customerEdit: 'تعديل عميل',
  rentals: 'التأجيرات',
  rentalNew: 'إنشاء تأجير',
  rentalDetails: 'تفاصيل التأجير',
  payments: 'المدفوعات',
  invoices: 'الفواتير',
  reports: 'التقارير',
  auditLogs: 'سجلات النظام',
  employees: 'الموظفين',
  employeeEdit: 'تعديل موظف',
  settings: 'الإعدادات',
};
